from enum import Enum

class UserStateEnum(Enum):
    MAIN_MENU = "main_menu"
    SURVEY_START = "survey_start"
    SURVEY_INSURANCE_TYPE = "survey_insurance_type"
    SURVEY_AUTO_SUBTYPE = "survey_auto_subtype"
    SURVEY_PRIORITY = "survey_priority"
    SURVEY_CAR_BRAND = "survey_car_brand"
    SURVEY_CAR_YEAR = "survey_car_year"
    SURVEY_CAR_VIN = "survey_car_vin"
    SURVEY_DATA_COLLECTION = "survey_data_collection"
    SURVEY_ADDRESS = "survey_address"
    SURVEY_AREA = "survey_area"
    SURVEY_TRAVEL_COUNTRY = "survey_travel_country"
    SURVEY_TRAVEL_DATES = "survey_travel_dates"
    SURVEY_AGE = "survey_age"
    SURVEY_RESULTS = "survey_results"
    PRODUCT_INFO = "product_info"
    PRODUCT_SELECTION = "product_selection"
    APPLICATION_START = "application_start"
    APPLICATION_FIO = "application_fio"
    APPLICATION_PHONE = "application_phone"
    APPLICATION_EMAIL = "application_email"
    APPLICATION_CONTACT_METHOD = "application_contact_method"
    APPLICATION_CONFIRMATION = "application_confirmation"
    APPLICATION_COMPLETED = "application_completed"
    OPERATOR_REQUEST = "operator_request"
